name: skat_service
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.3.0+1
  sqlite3: ^0.1.8

dev_dependencies:
  aqueduct_test: ^1.0.0
  test: ^1.0.0
